CREATE TABLE USUARIOS(
  USUARIO VARCHAR(400) NOT NULL,
  PASSWORD VARCHAR(700) NOT NULL,
  CORREO VARCHAR(700) NOT NULL,
  CONSTRAINT PK_USUARIOS PRIMARY KEY(USUARIO)
);
CREATE TABLE NOTAS(
  URL VARCHAR(700) NOT NULL,
  TITULO VARCHAR(700) NOT NULL,
  TEXTO TEXT,
  USUARIO VARCHAR(400) NOT NULL,
  CONSTRAINT PK_NOTAS PRIMARY KEY(URL),
  CONSTRAINT FK_NOTAS FOREIGN KEY(USUARIO) REFERENCES USUARIOS(USUARIO)
);

/*
Ejemplo de la creación de un usuario: 
  INSERT INTO USUARIOS(USUARIO,PASSWORD,CORREO) VALUES("pepitogrillo","1234","pepitogrillo@dominio.com");
*/
